linters:
  enable:
    - bodyclose
    - errcheck
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - rowserrcheck
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/realkarych/seqwall
  misspell:
    locale: US

issues:
  include:
    - EXC0002
